region_id: new_york
data_root: /network/rit/lab/basulab/Projects/DFS/DATA
region_tag: NYS
boundary:
  gadm_file: /network/rit/lab/basulab/Harish/ResearchOS/Projects/Active/Sparse-to-grided-deep-interpolation/git_repos/Sparse_to_dense_meteorological_variables/data/geospatial/gadm_410.gpkg
  country: United States
  state: New York
  buffer_m: 5000
grid:
  URMA:
    type: curvilinear
    dims:
    - y
    - x
    n0: 256
    n1: 288
    crop:
      y_start: 830
      x_start: 1800
  HRRR:
    type: curvilinear
    dims:
    - y
    - x
    n0: 611
    n1: 574
    crop:
      y_start: 447
      x_start: 1224
  ERA5:
    type: separable
    dims:
    - latitude
    - longitude
    n0: 40
    n1: 56
    crop:
      latitude_start: 168
      longitude_start: 1112
  EDDEv2:
    type: curvilinear
    dims:
    - y
    - x
    n0: 164
    n1: 165
    crop:
      y_start: 206
      x_start: 324
  Ouranos:
    type: curvilinear
    dims:
    - rlat
    - rlon
    n0: 172
    n1: 174
    crop:
      rlat_start: 202
      rlon_start: 383
  ICON:
    type: unstructured
    dims:
    - cell
    n_selected: 7083
    cell_mask_file: configs/regions/masks/new_york_ICON_cell_mask.nc
